apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ap-south-1

managedNodeGroups:
  - name: ng-1
    instanceType: m5.large
    spot: true
    desiredCapacity: 3
    ssh:
      publicKeyName: k8resc
